- name: Mongo DB Setup 
  hosts: all
  remote_user: vagrant
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
      # MongoDB Version
    mongodb_install_version_major: 4
    mongodb_install_version_minor: 4
    mongodb_install_version_patch: "*"


    # Ubuntu
    mongodb_enable_apt_repository: true


    # MongoDB Configuration
    mongodb_conf_file: /etc/mongodb/mongod.conf
    mongodb_conf_db_dir: /data/mongo-data
    mongodb_conf_log_dir: /var/log/mongodb
    mongodb_conf_dbEngine: wiredTiger
    mongodb_conf_auth: true
    mongodb_conf_bindIp: "0.0.0.0"
    mongodb_conf_journal: true
    mongodb_conf_maxConns: 51200
    mongodb_conf_port: 27017
    mongodb_conf_oplogSize: 1024
    mongodb_conf_cloudmonitoring: "off"


    # Systemd Units
    mongodb_daemon_unitfile: /etc/systemd/system/mongod.service

    # Replicset configuration
    mongodb_replication_enabled: true   #false will create a standalone MongoDB instance
    mongodb_replication_key_file: /etc/mongodb/repl.key
    mongodb_replication_set_name: 'rs01'


    # PyMongo Configuration
    mongodb_pymongo_pip_version: 3.7.1

    # Account configuration
    mongodb_root_account: vagrant
    mongodb_root_password: "jasemsia"

    mongodb_admin_account: dbadmin
    mongodb_admin_password: "p@ssw0rd"

    mongodb_backup_account: backupadmin
    mongodb_backup_password: "p@ssw0rd"
    ansible_default_ipv4: 192.168.33.1


  roles:
    - mongodb-replicaset
