---
- name: Install wget
  apt:
    name: "wget"
    force_apt_get: True

- name: Add MongoDB public GPG Key
  command: wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -

- name: Add MongoDB 4 Repo
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse
    state: present
    filename: mongodb-org-4.4

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
    force_apt_get: True

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: True

- name: Install MongoDB packages
  apt:
    name: "{{ mongo_packages }}"
    force_apt_get: True

- name: Install python3-pip
  apt:
    name: "python3-pip"
    force_apt_get: True

- name: Install the latest pymongo package
  pip: 
    name: pymongo
    state: latest 
    use_mirrors: no